// <auto-generated />
using System;
using ContactList.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactList.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241124181355_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContactList.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d72022b3-62e1-4de3-abca-b96adc9ec313"),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = new Guid("4d2c760c-794d-4544-bf90-ce00743d3b1c"),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "987-654-3210"
                        },
                        new
                        {
                            Id = new Guid("37f46b4b-bb6b-4aa6-9544-d141f97cbbc2"),
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            PhoneNumber = "456-789-0123"
                        },
                        new
                        {
                            Id = new Guid("6920f9e1-4f26-488e-b2d1-d58823c35af3"),
                            Email = "alice.johnson@example.com",
                            FirstName = "Alice",
                            LastName = "Johnson",
                            PhoneNumber = "321-654-0987"
                        },
                        new
                        {
                            Id = new Guid("aad1fea2-d857-4d17-b684-9f44baad605e"),
                            Email = "charlie.williams@example.com",
                            FirstName = "Charlie",
                            LastName = "Williams",
                            PhoneNumber = "123-123-1234"
                        },
                        new
                        {
                            Id = new Guid("5205f1fc-ee07-4521-b624-a76ca8f40c30"),
                            Email = "emily.davis@example.com",
                            FirstName = "Emily",
                            LastName = "Davis",
                            PhoneNumber = "987-987-9876"
                        },
                        new
                        {
                            Id = new Guid("817f4af0-d1aa-4821-bd34-f641f4720b40"),
                            Email = "michael.wilson@example.com",
                            FirstName = "Michael",
                            LastName = "Wilson",
                            PhoneNumber = "456-456-4567"
                        },
                        new
                        {
                            Id = new Guid("b2ecb682-f25b-4ee1-9e7d-f537bcd1da05"),
                            Email = "olivia.taylor@example.com",
                            FirstName = "Olivia",
                            LastName = "Taylor",
                            PhoneNumber = "789-789-7890"
                        },
                        new
                        {
                            Id = new Guid("213cdceb-06fe-4049-8fa0-c8c4f589b076"),
                            Email = "james.anderson@example.com",
                            FirstName = "James",
                            LastName = "Anderson",
                            PhoneNumber = "234-567-8901"
                        },
                        new
                        {
                            Id = new Guid("c1a92de7-6346-4235-a92d-ba5d5c09efa6"),
                            Email = "sophia.thomas@example.com",
                            FirstName = "Sophia",
                            LastName = "Thomas",
                            PhoneNumber = "890-123-4567"
                        },
                        new
                        {
                            Id = new Guid("132a8a45-6e10-4cd3-be5d-d673bf515324"),
                            Email = "william.moore@example.com",
                            FirstName = "William",
                            LastName = "Moore",
                            PhoneNumber = "567-890-1234"
                        },
                        new
                        {
                            Id = new Guid("b6ef5175-46ab-44da-ae5b-e1cd66bf7b79"),
                            Email = "isabella.martin@example.com",
                            FirstName = "Isabella",
                            LastName = "Martin",
                            PhoneNumber = "345-678-9012"
                        },
                        new
                        {
                            Id = new Guid("334dff84-0e0a-447a-ba05-6c9935d2a9d3"),
                            Email = "alexander.harris@example.com",
                            FirstName = "Alexander",
                            LastName = "Harris",
                            PhoneNumber = "901-234-5678"
                        },
                        new
                        {
                            Id = new Guid("e8ed0b6a-041c-4392-8dc9-cdced5996884"),
                            Email = "mia.clark@example.com",
                            FirstName = "Mia",
                            LastName = "Clark",
                            PhoneNumber = "678-901-2345"
                        },
                        new
                        {
                            Id = new Guid("0b7ee150-4970-4354-b8ad-2d68b5aff2c2"),
                            Email = "daniel.martinez@example.com",
                            FirstName = "Daniel",
                            LastName = "Martinez",
                            PhoneNumber = "123-456-7891"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
